config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get ':id/offers_made', to: 'profiles#offers_made'
  get ':id/offers_received', to: 'profiles#offers_received'
  get ':id/profiles', to: 'profiles#profile', :as => 'profile'
  get ':id/my_pets', to: 'profiles#my_pets', :as => 'my_pets'

  resources :pets do
    resources :offers, except: [:show]
    get 'offers/:id/accept', to: 'offers#accept', :as => "accepted"
    get 'offers/:id/reject', to: 'offers#reject', :as => "rejected"

    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :pet
  validates :total, numericality: { greater_than: 0, message: "End date not correct!" }
  validates :end_date, presence: true
  validates :starting_date, presence: true
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :offers, dependent: :destroy
  has_many :reviews

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_address,
    against: [ :name, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  has_one_attached :photo
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :price_per_hour, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :pet
  validates :comment, length: { minimum: 5 }
  validates :rating, inclusion: { in: 1..5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pets
  has_many :offers
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  #include Pundit
  #rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  #after_action :verify_authorized, except: :index, unless: :skip_pundit?
  #after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
  end

  private

  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(request.referrer || root_path)
  # end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :find_pet, except: [:my_offers]

  def index
    @offers = @pet.offers#policy_scope(@pet.offers)
  end

  def new
    if @pet.user == current_user
      redirect_to root_path
    end
    @offer = Offer.new
  end
  def create
    @offer = Offer.new(offer_params)
    add_offer_parameters
    if @offer.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end
  def edit
    @offer = Offer.find(params[:id])

  end
  def update
    @offer = Offer.find(params[:id])
    add_offer_parameters
      if @offer.update(offer_params)
          redirect_to pet_path(@pet)
    else
      render :edit
    end
  end
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to pet_path(@pet)

  end

  def my_offers
    @current_user = current_user
  end

  def accept
    offer = Offer.find(params[:id])
    offer.accepted = true
    if offer.update(accepted: 'accepted')
      redirect_to "/#{current_user.id}/offers_received"
    end
  end

  def reject
    offer = Offer.find(params[:id])
    offer.accepted = true
    if offer.update(accepted: 'rejected')
      redirect_to "/#{current_user.id}/offers_received"
    end
  end

  private

  def find_pet
    @pet = Pet.find(params[:pet_id])
    # authorize @pet
  end

  def add_offer_parameters
    if !params[:offer][:starting_date].empty? && !params[:offer][:end_date].empty?
      start_date = Date.parse params[:offer][:starting_date]
      end_date =Date.parse params[:offer][:end_date]
      price = (end_date- start_date) * @pet.price_per_hour
      @offer.total = price.to_i
      @offer.user = current_user
      @offer.pet = @pet
    end
  end

  def offer_params
    params.require(:offer).permit(:starting_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @user =current_user
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:edit, :update, :destroy, :show]

  def index
    #@pets = Pet.all.order(:id)
    if params[:query].present?
      @pets = Pet.search_by_name_and_address(params[:query])
    else
      @pets = Pet.all.order(:id)
    end
    @markers = @pets.geocoded.map do |pet|
      {
        lat: pet.latitude,
        lng: pet.longitude,
        image_url: helpers.asset_url('dog-park.svg'),
        info_window: render_to_string(partial: "info_window", locals: { pet: pet })
        }
    end
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to pets_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pet.user == current_user
      if @pet.update(pet_params)
        redirect_to pet_path(@pet)
      else
        render :edit
      end
    end
  end

  def destroy
    if @pet.user == current_user
      @pet.destroy
      redirect_to pets_path
    end
  end

  def show
    @pet = Pet.find(params[:id])
    @offer = Offer.new
    @review = Review.new
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :address, :price_per_hour, :description, :category, :photo)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def profile
    if current_user == User.find(params[:id])
      @user = current_user
      #authorize @user
    else
      redirect_to profile_path(current_user)
      #authorize current_user
    end
  end

  def offers_made
    @user = current_user
    #authorize @user
  end

  def offers_received
    @pets = current_user.pets
    #authorize @pets
  end

  def my_pets
    @my_pets = current_user.pets
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_pet
  before_action :authenticate_user!

  def index
    @reviews = @pet.reviews
  end

  def new
    @pet = Pet.find(params[:pet_id])
    @review = Review.new
  end

  def create
    @pet = Pet.find(params[:pet_id])
    @review = Review.new(review_params)
    @review.pet = @pet
    @review.user = current_user
    if @review.save
      redirect_to pet_path(@pet)
    else
      @offer = Offer.new
      render 'pets/show'
    end
  end

  private

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whosthegoodboy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_pack_tag 'application' %>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/flashes' %>

    <%= render "shared/navbar" %>

    <%= yield %>
  </body>
</html>

app/views/offers/edit.html.erb
<div  class='w-50 form shadow p-3 mb-5 rounded' style="background-color:#f9e5de">
  <% if @offer.errors.any? %>
    <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= @offer.errors.messages[:total][0] %></li>
      <% end %>
      </ul>
    <% end %>
  <%= simple_form_for [ @pet, @offer ] do |f| %>
    <%= f.input :starting_date, as: :date, html5: true%>
    <%= f.input :end_date, as: :date, html5: true%>

    <%= f.submit "Submit review", class: "style-btn-form" %>
  <% end %>
</div>

app/views/offers/index.html.erb
<ul>
  <%@offers.each do |offer| %>
    <li><p>starting date: <%= offer.starting_date %></p>
      <p>ending date:<%= offer.end_date %></p>
      <p>Total price:<%= offer.total %></p>
      <%= link_to "Edit", "/pets/#{@pet.id}/offers/#{offer.id}/edit" %>
      <%= link_to "Remove",
                  "/pets/#{@pet.id}/offers/#{offer.id}",
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
    </li>
  <%end %>
</ul>

app/views/offers/my_offers.html.erb
<ul>
  <%@current_user.offers.each do |offer| %>
    <li><p>start date: <%= offer.starting_date %></p>
      <p>end date: <%= offer.end_date %></p>
      <p>start date: <%= offer.starting_date %></p>
      <p>Pet: <%= offer.pet.name %></p>
    </li>
  <%end %>
</ul>
<ul>
  <%@current_user.pets.each do |pet| %>
    <%pet.offers.each do |offer| %>
    <li><p>start date: <%= offer.starting_date %></p>
      <p>end date: <%= offer.end_date %></p>
      <p>start date: <%= offer.starting_date %></p>
      <p>Pet: <%= offer.pet.name %></p>
    </li>
  <%end %>
  <%end %>
</ul>

app/views/offers/new.html.erb
<div  class='w-50 form shadow p-3 mb-5 bg-white rounded'>
<h1>Make your offer</h1><br>
  <%= simple_form_for [ @pet, @offer ] do |f| %>
    <%= f.input :starting_date, as: :date, html5: true%>
    <%= f.input :end_date, as: :date, html5: true%>
    <%= f.submit "Submit review", class: "style-btn-form" %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row justify-content-center">

    <div class="text-intro">
      <p><strong>Who's the good boy</strong> is the ultimate platform to fill your need for cuteness by renting the cutest pets near you!</p>

      <p>The concept was born in 2022, after Helene, Bruno and Noah thought of a new and nice way to allow people without pets to experience having one for a limited period of time, before committing to getting a pet</p>
      <p><strong>Who's the good boy</strong> can also be used by owners to rent out their pets when they are too busy to walk their lovely dog or when they go on holidays and need a <strong>safe</strong> solution to take care of their loved one.</p>
    </div>

    <div class="link">
      <p><br><%= link_to "View all good boys ", pets_path %></p>
    </div>
  </div>


  <%= image_tag 'home.jpg', href:"/pets", class: "home_image" %>
</div>
<br>

app/views/pets/_info_window.html.erb
<h4><%= link_to pet.name, pet_path(pet)%></h4><br>
<% if pet.photo.attached? %>
<%= cl_image_tag pet.photo.key, height: 50,width:50, crop: :fill%><br>
<% end %>
<p><%= pet.address %></p>

app/views/pets/edit.html.erb
<div  class='w-50 form shadow p-3 mb-5 rounded' style="background-color:#f9e5de">
  <%= simple_form_for @pet do |f| %>
    <%= f.input :name %>
    <%= f.input :address%>
    <%= f.input :description%>
    <%= f.input :category%>
    <%= f.input :price_per_hour%>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Update pet", class: "style-btn-form" %>
  <% end %>
</div>

app/views/pets/index.html.erb
<div id="index-container" >

  <!-- Below is the div that just is a 2 column grid for all pets on left and
  the map on the right-->
  <div class="parent d-flex">

    <!-- Below is the left column which contains all the pets -->
    <div class="pet-cards col-6">
      <%unless @pets.empty? %>
      <% @pets.each do |pet| %>
        <div class="pet-card">
          <% if pet.photo.attached? %>
            <%= cl_image_tag pet.photo.key, height: 200, width: 200, crop: :fill %>

          <% end %>

          <div class="pet-card-infos">
            <div id="address">
              <%= pet.address.capitalize %>
            </div>

          <div id="name">
            <h1><%= link_to pet.name.upcase,pet_path(pet) %></h1>
          </div>

            <h3><%= pet.category %></h3>

          <div class="description">
            <p><%= pet.description.capitalize %> <% if pet.description.length > 20%><%= link_to "...", pet_path(pet) %><%end%></p>

          </div>
            <p><%= pet.price_per_hour %> € / h</p>

          </div>
        </div>
      <% end %>
      <%else %>
        <h1>No pets found!</h1>
      <%end %>
    </div>


    <!-- Below is the right column with the map -->

    <div class="map_card col-6" id="map"
      style=" height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>



  </div>
</div>

app/views/pets/new.html.erb
<div class="new-pet-form">
  <div  class='w-50 form shadow p-3 mb-5 rounded' style="background-color:#f9e5de"id="new-pet-form">
    <%= simple_form_for @pet do |f| %>
      <%= f.input :name %>
      <%= f.input :address%>
      <%= f.input :description%>
      <%= f.input :category%>
      <%= f.input :price_per_hour%>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Create pet", class: "style-btn-form" %>
    <% end %>
  </div>
</div>

app/views/pets/show.html.erb
<div  class='w-50 form'>

  <div class="container shadow p-3 mb-5 rounded ", style="background-color:#f9e5de" id="background-color" >
    <h3 class="text-center"><%= @pet.name.upcase %> <br><br></h3>
    <%if @pet.photo.attached? %>
      <div class="d-flex justify-content-center" >
        <%= cl_image_tag @pet.photo.key, height: 200, width: 200, crop: :fill, :style => "border-radius: 50%" %>
      </div>

    <%end %> <br>
    <div class='shadow bg-white rounded p-3 mb-1'>
      <h4>Category:</h4> <p><%= @pet.category %></p>
    </div>
    <div class='shadow bg-white rounded p-3 mb-1'>

       <h4>Description :</h4> <p> <%= @pet.description %> </p>

    </div>
    <div class='shadow bg-white rounded p-3 mb-1'>
      <h4>Price:</h4> <p><%= @pet.price_per_hour %> €/H</p>
    </div><br><br>
      <% unless @pet.user == current_user %>
    <div class='shadow bg-white rounded p-3'>
      <h4>Make your offer</h4><br>
      <%= simple_form_for [ @pet, @offer ] do |f| %>
        <%= f.input :starting_date, as: :date, html5: true, input_html: { class: 'text-secondary' }%>
        <%= f.input :end_date, as: :date, html5: true, input_html: { class: 'text-secondary' }%>
        <%= f.submit "Submit offer", class: "submit-btn" %>
      <% end %>
    </div>
      <% end %>



<br><br>
    <div class='shadow bg-white rounded p-3' style="color:#6d6c6c">
     <div class="reviews">
      <h4><%= pluralize @pet.reviews.size, "review" %></h4><br>
        <% if @pet.reviews.blank? %>
    Be the first to leave a review for <%= @pet.name %>
        <% else %>
        <div>
          <% @pet.reviews.each do |review| %>
          <% if review.user.full_name %>
            <h5 class="user"><%= review.user.full_name %></h5>
          <%end %>
            <p><%= review.comment %></p>
            <p class="pet-review pb-2"><%= review.rating %></p><br>

          <% end %>
        </div>
      <% end %>
      </div>
      <br>
      <div class="leave-a-review">
      <%= simple_form_for([ @pet, @review ]) do |f| %>
        <%= f.input :comment, as: :text %>
        <%= f.input :rating, as: :integer, input_html: {min: 1, max: 5} %>
        <%= f.button :submit, class: "submit-btn" %>
      <% end %>
      </div>
    </div>




      <br><%= link_to "go back to all the pets", pets_path ,class:'go-back-btn'%> <br>
    </div>
  </div><br>

app/views/profiles/index.html.erb
<%= link_to 'Offers Made', "/#{@user.id}/offers_made" %> <br>
<%= link_to 'Offers received ', "/#{@user.id}/offers_received" %> <br>
<%= link_to 'Change password ', "/users/edit" %> <br>
<%= link_to "Logout", destroy_user_session_path, :method => :delete  %>

app/views/profiles/my_pets.html.erb
<div class='container d-flex w-50 flex-column divOffer shadow p-3 mb-5 rounded' style="background-color:#f9e5de">
    <h1 >Your account</h1>
    <div class='d-flex  flex-column  '>
      <% @my_pets.each do |pet| %>
        <div class='d-flex shadow p-3 mb-5 bg-white rounded'>
          <%if pet.photo.key %>
            <%= cl_image_tag pet.photo.key, height: 120,width:100, crop: :fill %>
          <%end %>
          <div class="d-flex flex-column pl-3">
            <%= pet.name %>
            <%= link_to 'Edit',edit_pet_path(pet) ,class:'style-btn-form btn-sm' %>
           <%= link_to "Delete",
                  pet_path(pet),
                  method: :delete,
                  data: { confirm: "Are you sure?" },class:'style-btn-form btn-sm' %>
          </div>
        </div><br>
      <%end %><br>
    </div>

</div>

app/views/profiles/offers_made.html.erb
<div class='container w-50 shadow p-3 mb-5 rounded'style="background-color:#f9e5de">
  <ul>
    <%@current_user.offers.each do |offer| %>
    <li>
      <div class='card-offer-made shadow bg-white rounded'>
        <p>Start date: <%= offer.starting_date %> <br>
          End date: <%= offer.end_date %><br>
          Pet: <%= offer.pet.name %> <br>
          Accepted: <%= offer.accepted %></p>
      </div>
    </li>
    <%end %>
  </ul>
</div>
<div class="container ">
<%= link_to 'Back to profile',profile_path(current_user) , class: "style-form-btn go-back" %>
</div>

app/views/profiles/offers_received.html.erb
<div class="container w-50 shadow p-3 mb-5  rounded" style="background-color:#f9e5de">
  <ul>
    <%@current_user.pets.each do |pet| %>
      <%pet.offers.each do |offer| %>
      <li>
        <div class='card-offer-made shadow bg-white rounded' >
          <p>start date: <%= offer.starting_date %> <br>
          end date: <%= offer.end_date %><br>
          Pet: <%= offer.pet.name %><br>
          Accepted: <%= offer.accepted %><br>
          <%  if offer.accepted != 'accepted'%>
            <%= link_to 'Accept offer', pet_accepted_path(offer.pet,offer),class:"btn btn-success"%>
          <%end %>
          <%  if offer.accepted != 'rejected'%>
            <%= link_to 'Reject offer', pet_rejected_path(offer.pet,offer),class:"btn btn-danger"%>
          <%end %>
        </div>

        </li>
      <%end %>
    <%end %>
  </ul>
</div>
<div class="container ">
<%= link_to 'Back to profile',profile_path(current_user) , class: "style-btn-form go-back" %>

</div>

app/views/profiles/profile.html.erb
<div class='container d-flex flex-column divOffer shadow p-3 mb-5 bg-white rounded'>
  <div class='centered_div'>
    <h1 >Your account</h1>
    <div class='d-flex flex-wrap '>
      <div class='card-offer shadow bg-white rounded'><%= link_to "/#{@user.id}/offers_made"  do %>
        <div class='link-content'> <h4>Made offers</h4>  <p>View all the offer you have made</p></div>
        <% end %>
      <br></div>
      <div class='card-offer shadow bg-white rounded'><%= link_to "/#{@user.id}/offers_received" do %>
        <div class='link-content'> <h4>Received offers</h4>  <p>View, accept or reject offers made to you</p></div>
    <% end %> <br></div>
    <div class='card-offer shadow bg-white rounded'><%= link_to my_pets_path do %>
      <div class='link-content'> <h4>My pets</h4>  <p>View, delete or edit your pets</p></div>
    <% end %> <br></div>
      <div class='card-offer shadow bg-white rounded'><%= link_to "/users/edit" do %>
    <div class='link-content'> <h4>Reset password</h4>  <p>Forgot your password?</p></div>
    <% end %> <br></div>
    </div>


  </div>
</div>

app/views/reviews/new.html.erb
Add a review for <%= @pet.name %>.

    <%= simple_form_for [@pet, @review] do |f| %>
      <%= f.input :comment, placeholder: 'Enter your comment' %>
      <%= f.number_field :rating, value: 1,min: 1, max: 5 %>
      <%= f.submit %>
      <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar" style="background-color: #f4f4f4;">

  <div class="navbar-container" id="navbar-container">
    <div class="col-sm title-nav ">
      <div class="logo ">
        <a class="navbar-brand " href="/" style="color:#d14413;;" >WHO'S THE GOOD BOY?</a>
      </div>
    </div>

    <div class='search-bar'>
      <%= form_tag pets_path, method: :get do %>
        <div class="col-sm d-flex column justify-content-center">

          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            id: "search-form-control",
            placeholder: "Find a pet"
          %>
          <%= submit_tag "Search", class: "btn btn-ghost" %>

        </div>
        <% end %>

    </div>


    <div class="col-sm d-flex justify-content-end"></div>
      <div class='d-flex column '>
        <%unless current_user %>
          <a class="sign-up btn  " href="/users/sign_up">Sign up</a>
          <a class="log-in btn    " href="/users/sign_in">Log in</a>
        <%else %>
          <button class="btn-menu dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             MENU
          </button>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to 'Create Pet',new_pet_path , class: "dropdown-item log-out" %>
          <%if current_user %>
            <%= link_to 'Your account',profile_path(current_user) , class: "dropdown-item log-out" %>
          <%end %>
          <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "dropdown-item log-out" %>

        </div>

        <%end %>
      </div>
    </div>
  </div>
</div>